### PR TITLE
Update iOS cross-compile instructions

### PR DESCRIPTION
**Pull request by schuay**
Pointer compression is unsupported and must be disabled.

### CODE REVIEW

**Comment by backes** [comment]
Is this just because of the compiler error with V8_ASSUME_ALIGNED, or do we expect more problems?
If it's only the compile error, we could just avoid using __builtin_assume_aligned on iOS.

**Comment by schuay** [comment]
> Is this just because of the compiler error with V8_ASSUME_ALIGNED, or do we expect more problems?
> If it's only the compile error, we could just avoid using __builtin_assume_aligned on iOS.

The V8_ASSUME_ALIGNED error was the motivation yes, and I vaguely recall ptr-compression problems on iOS builds in the past. Do you mean that the root cause is not ptrcomp but the V8_ASSUME_ALIGNED macro?

**Comment by backes** [comment]
> > Is this just because of the compiler error with V8_ASSUME_ALIGNED, or do we expect more problems?
> > If it's only the compile error, we could just avoid using __builtin_assume_aligned on iOS.
> 
> The V8_ASSUME_ALIGNED error was the motivation yes, and I vaguely recall ptr-compression problems on iOS builds in the past. Do you mean that the root cause is not ptrcomp but the V8_ASSUME_ALIGNED macro?

I don't know about further issues - but as discussed offline it seems like there were also other issues. In that case, let's just recommend to disable it on iOS.

**Review by backes — APPROVED** [review]

**Comment by schuay** [comment]
> > > Is this just because of the compiler error with V8_ASSUME_ALIGNED, or do we expect more problems?
> > > If it's only the compile error, we could just avoid using __builtin_assume_aligned on iOS.
> > 
> > 
> > The V8_ASSUME_ALIGNED error was the motivation yes, and I vaguely recall ptr-compression problems on iOS builds in the past. Do you mean that the root cause is not ptrcomp but the V8_ASSUME_ALIGNED macro?
> 
> I don't know about further issues - but as discussed offline it seems like there were also other issues. In that case, let's just recommend to disable it on iOS.

Thanks! For posterity, the issue back then was that iOS doesn't support 4GB reservations needed for ptrcomp.

**Pull request merged**
