### PR TITLE
Fix figure markup

### PR DESCRIPTION
**Pull request by tomayac**
Without the paragraph, this renders as `` instead of `<figure>`

### CODE REVIEW

**Comment by RReverser** [comment]
Thanks!

**Comment by mathiasbynens** [comment]
> Without the paragraph, this renders as  instead of <figure>

I'm surprised the linter didn't catch that. It certainly complained about lack of newline before `<figure>` back when that was how we did it. Any ideas, @rreverser? Maybe there's a markdownlint rule we can just enable?

**Comment by RReverser** [comment]
Not sure there is a built-in markdownlint rule, because technically it's possible and allowed to have inline images as well, for which this is a valid syntax.

However, if we never use inline images, it should be fairly straighforward to add such custom check in `md-embed-image.js`.

**Comment by mathiasbynens** [comment]
> However, if we never use inline images, it should be fairly straighforward to add such custom check in `md-embed-image.js`.

We never do, and I don't imagine ever needing to do so. Until a use case comes up, adding that check sounds great!

**Pull request merged**
