### PR TITLE
chore: Use Travis Deploy Script provider

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Thanks!

**Comment by mathiasbynens** [comment]
This fails because it can’t find the `firebase`: https://travis-ci.com/v8/v8.dev/builds/112367736#L707 I’ll revert. Let’s just stick to what we have, it works fine.

**Comment by nschonni** [comment]
No problem. Might be good to ask if Travis is going to provide Firebase as a provider

**Comment by mathiasbynens** [comment]
They do already support Travis as a provider, but I ran into similar issues when I tried that. The current approach is the first thing I tried that actually worked 🤷

**Pull request merged**
