### PR TITLE
added Ingvar Stepanyan's avatar

### PR DESCRIPTION
**Pull request by jduran7**
Added 96x96px and 192x192px jpg's of Ingvar Stepanyan's avatar.

### CODE REVIEW

**Comment by jduran7** [comment]
@googlebot I signed it!

**Comment by mathiasbynens** [comment]
Hey @jduran7! https://github.com/v8/v8.dev/issues/218 was actually assigned to @RReverser. Let's let him choose his own preferred image :)

(Oh, and also: any images should be run through Squoosh/ImageOptim before including them in a PR.)

**Comment by RReverser** [comment]
Haha, indeed, I was supposed to add it myself. For what it's worth, this is the image I was planning to use too, so I'm fine either way, but yeah, it should probably be optimised :)

**Comment by jduran7** [comment]
Woops, my bad!

**Comment by mathiasbynens** [comment]
@jduran7 Per https://github.com/v8/v8.dev/pull/221#issuecomment-521166792 it's fine to continue to use this PR, if you want. You'd just have to optimize the images. Would you be up for that?

**Comment by jduran7** [comment]
Sure, I'll take care of that

**Comment by mathiasbynens** [comment]
FWIW, I tend to use [Squoosh](https://squoosh.app) with MozJPEG @ quality=75, and then run the result through `ImageOptim.app` with “optimization level” set to “insane” for further savings.

**Comment by RReverser** [comment]
One nit: the current image seems somewhat blurry. Was it taken from my front page (more specifically, https://rreverser.com/content/images/2018/06/sq_DSC5437-2.jpg)?

**Comment by jduran7** [comment]
@RReverser I had taken it from your Github profile, but this time I used the one from the link you provided.

**Comment by mathiasbynens** [comment]
File sizes look a lot better now! Thank you, @jduran7 :)

**Comment by RReverser** [comment]
The images (particularly, the small one) still looks pretty blurry, especially on retina... @mathiasbynens points out that these images are also smaller than most avatars, so maybe the compression settings chosen here were just a bit overzealous?

**Comment by RReverser** [comment]
Sorry @jduran7, I think I'll do this one myself after all, as I want to play around with quality a bit.

**Comment by jduran7** [comment]
No worries! yes, I also agree that the images could do with a bit less compression, but that's obviously up to you to decide.

**Pull request closed without merging**
