### PR TITLE
Update Firefox support for public class fields

### PR DESCRIPTION
**Pull request by Arkni**
Firefox added support for public class fields as of the release 69

See https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/69#JavaScript

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Unfortunately, there is no separation between instance and static public fields (latter is not implemented in Firefox 69) in feature support table, so this change is not quite correct. @mathiasbynens should "Support for public class fields" be splitted into "Support for instance public class fields" and "Support for static class fields"?

**Comment by Arkni** [comment]
Hi @chicoxyzzy,

I read your reply in the Twitter thread and I saw the other PR.

Splitting the section into two implies that the other section about private class fields should be split too.

If splitting the section is not an option, I think as a solution, the component that renders the support listings can be adapted to show partial implementations as yellow/orange with possibility to add a note bellow or a tooltip.

**Comment by chicoxyzzy** [comment]
> If splitting the section is not an option, I think as a solution, the component that renders the support listings can be adapted to show partial implementations as yellow/orange with possibility to add a note bellow or a tooltip.

Yes, I think that `partial` value for feature support is a good option. There is no such value, but I think it could be added easily https://github.com/v8/v8.dev/blob/master/feature-support.js

**Comment by adalinesimonian** [comment]
Completely missed this PR while making one of my own. Thought it was a tiny change no one could have possibly noticed. Oh well, consider this a bump.

**Comment by mathiasbynens** [comment]
I've added support for "partial feature support" in 725d6776f7f8656fbd16237075071773cdfa88a7, and have updated this patch to use it. This now looks good to go. Thanks, everyone!

**Comment by Arkni** [comment]
Thanks a lot @mathiasbynens for working on this. And sorry I wasn't able to work on it due to some struggles the last few months.

**Pull request merged**
