### PR TITLE
Add WasmGC porting blogpost

### PR DESCRIPTION
**Pull request by kripken**
Already reviewed by @tomayac @ajklein @tlively

### CODE REVIEW

**Comment by kripken** [comment]
This was waiting on Chrome 119, which supports WasmGC (and so the demo runs there), and which is now being launched: https://chromereleases.googleblog.com/2023/10/stable-channel-update-for-desktop_31.html

**Review by tomayac — APPROVED** [review]
Non-owner LGTM, based on the Google doc version that I have reviewed.

**Review by ajklein — APPROVED** [review]
lgtm

**Comment by tomayac** [comment]
@kripken Congratulations on the publication. Just opened https://github.com/GoogleChrome/developer.chrome.com/pull/7730 to interlink the articles.

**Pull request merged**
