### PR TITLE
Actualize core-js data

### PR DESCRIPTION
**Pull request by zloirock**
https://github.com/v8/v8.dev/pull/564#issuecomment-875916452

### CODE REVIEW

**Comment by zloirock** [comment]
@googlebot I signed it!

**Comment by RReverser** [comment]
For things you switched from `no` to `yes` - does Babel include those things by default or do you need some special flags? It would be useful to link directly to Babel docs if possible.

**Comment by zloirock** [comment]
What do you mean by "does Babel include those things by default"? Sure - default polyfilling for Babel is just import `core-js` polyfills. And yes, all they are included by default (even stage 3 `Object.hasOwn`) also in `preset-env` `usage` mode, in `runtime` and in `babel-polyfills`. Babel hasn't docs about each feature polyfill - Babel is about syntax, `core-js` about built-ins.

> [Babel offers polyfills through the core-js project.](https://v8.dev/features/support)

**Comment by RReverser** [comment]
> And yes, all they are included by default

Thanks, yeah, that's what I wanted to know - whether they are actually included by Babel by default or user needs to import corresponding polyfills from core-js directly.

**Comment by zloirock** [comment]
@mathiasbynens

**Review by RReverser — APPROVED** [review]

**Pull request merged**
