### PR TITLE
Enable cache travis

### PR DESCRIPTION
**Pull request by aymen94**
Speeds up future Travis builds.

### CODE REVIEW

**Comment by aymen94** [comment]
I signed it!

**Comment by mathiasbynens** [comment]
@aymen94 Could you please double-check? It doesn’t look like you used this GitHub handle (aymen94) when you signed the CLA.

**Comment by aymen94** [comment]
@mathiasbynens I signed it!

**Comment by mathiasbynens** [comment]
@aymen94 The bot is still not happy. Are you sure you’ve entered your GitHub username correctly? (It’s not in the system.)

**Comment by aymen94** [comment]
@mathiasbynens 
image

**Comment by mathiasbynens** [comment]
@aymen94 Yes, I know your email address is in the system. The problem is that your GitHub handle isn’t. We need both before we can accept any of your PRs. Is there a way for you to add your GitHub handle to your registration?

**Comment by aymen94** [comment]
@mathiasbynens I don't know, can you tell me?

**Comment by mathiasbynens** [comment]
@aymen94 I'm not familiar with the CLA system, unfortunately. Can you just fill out the form again, this time making sure to enter your GitHub username as well?

**Comment by mathiasbynens** [comment]
@aymen94 Do you want to follow up on this? If not, no worries, then we’ll close this PR.

**Comment by aymen94** [comment]
@mathiasbynens I close!

**Pull request closed without merging**
