### PR TITLE
Feature explainer: Object.hasOwn

### PR DESCRIPTION
**Pull request by victorgomes**

### CODE REVIEW

**Review by mathiasbynens — APPROVED** [review]

**Comment by mathiasbynens** [comment]
@RReverser Could you please help in getting this reviewed, landed, published, and announced? Thanks!

**Comment by RReverser** [comment]
Published: https://twitter.com/v8js/status/1410577516943847424

**Comment by zloirock** [comment]
> babel="no"

> Babel offers polyfills through the core-js project.

https://github.com/zloirock/core-js/releases/tag/v3.11.0

Please, next time check it.

**Comment by mathiasbynens** [comment]
@zloirock Could you submit a PR?

**Pull request merged**
