### PR TITLE
Use figcaption instead of title

### PR DESCRIPTION
**Pull request by RReverser**
This makes caption visible to all users and is more consistent with the rest of the blog.

### CODE REVIEW

**Comment by RReverser** [comment]
I see. That seems unusual, but I guess fine in this case. Just a shame that e.g. mobile users won't see same funny text, which `figcaption` would solve.

**Comment by mathiasbynens** [comment]
> Just a shame that e.g. mobile users won't see same funny text

They will if they interact with the image in the way that displays the `title` text. (E.g. on Chrome for Android, tap-and-hold on the image.)

**Comment by RReverser** [comment]
> They will if they interact with the image in the way that displays the title text.

Sure, but for that they need to know that image offers some interaction. I'd imaging most users don't tap-and-hold on images in blogs.

**Comment by mathiasbynens** [comment]
And that's fine for non-crucial captions like these.

**Comment by RReverser** [comment]
I don't know... I think we should be at least marking these images somehow if we don't offer a text that is definitely visible. But not sure which alternative way would be good then. Let's keep this open for now in case we can think of something better.

**Comment by LeszekSwirski** [comment]
Yeah, xkcd-style easter-egg was what I was going for here.

**Comment by RReverser** [comment]
TBH until you all told me, I didn't know XKCD has hover titles either 😅

**Comment by LeszekSwirski** [comment]
whole-new-world

**Comment by RReverser** [comment]
I guess I'll just close it, I don't have that strong opinion.

**Pull request closed without merging**
