### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by dine2014**

### CODE REVIEW

**Comment by RReverser** [comment]
Please sign CLA so that we could merge.

**Comment by dine2014** [comment]
Sorry, I don't have a Google account and it's hard for me to get one since Google is blocked in China. Would it be possible to submit the change yourself? I don't ask for credit for catching such small typos.

**Comment by RReverser** [comment]
@dine2014 Ah, that's unfortunate. I can fix the typo manually, but as a quick alternative, can you please try leaving a comment that just says `@googlebot I consent.`? That should work as an alternative.

**Comment by dine2014** [comment]
@googlebot I consent.

**Comment by RReverser** [comment]
Apparently, that doesn't work. Sorry!

I went ahead and fixed typo myself as per your suggestion. Thanks for the report!

**Pull request closed without merging**
