### PR TITLE
Correct name for class static initialization blocks

### PR DESCRIPTION
**Pull request by myshov**
A small fix that aligns the name of the feature with [proposal](https://github.com/tc39/proposal-class-static-block)

### CODE REVIEW

**Comment by RReverser** [comment]
@syg does this make sense?

**Review by syg — APPROVED** [review]
Renaming lgtm.

@RReverser does the index need to be updated or is it auto-generated?

**Comment by RReverser** [comment]
The index is autogenerated, although a redirect needs to be added to https://github.com/v8/v8.dev/blob/main/firebase.json to keep old URLs working. If not critical, I'd rather just keep filename/url intact and only change the contents.

**Comment by myshov** [comment]
@RReverser hey Ingvar! I restored the old name for the file

**Review by RReverser — APPROVED** [review]

**Comment by RReverser** [comment]
@myshov Thanks!

**Pull request merged**
